# Generated by Django 4.2.3 on 2023-08-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_accessrecord_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrecord',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
