# Generated by Django 4.2.3 on 2023-08-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_accessrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrecord',
            name='date',
            field=models.DateField(),
        ),
    ]
